v={'a','b','c','d','e',1,2,3,4,5,'rohini','thonny'}
print('a' not in v)
print('h' not in v)
print('e' not in v)
print('i' not in v)
print(2 not in v)
print(6 not in v)
print(5 not in v)
print(8 not in v)
print(3 not in v)
print('rohini' not in v)
print('mahitha' not in v)
print()
print()
print()
print()